/* soapH.h
   Generated by gSOAP 2.8.10 from ims.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE_ims__acceptFriendshipRequest
#define SOAP_TYPE_ims__acceptFriendshipRequest (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__acceptFriendshipRequest(struct soap*, struct ims__acceptFriendshipRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__acceptFriendshipRequest(struct soap*, const struct ims__acceptFriendshipRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__acceptFriendshipRequest(struct soap*, const char*, int, const struct ims__acceptFriendshipRequest *, const char*);
SOAP_FMAC3 struct ims__acceptFriendshipRequest * SOAP_FMAC4 soap_in_ims__acceptFriendshipRequest(struct soap*, const char*, struct ims__acceptFriendshipRequest *, const char*);

#ifndef soap_write_ims__acceptFriendshipRequest
#define soap_write_ims__acceptFriendshipRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__acceptFriendshipRequest(soap, data), 0) || soap_put_ims__acceptFriendshipRequest(soap, data, "ims:acceptFriendshipRequest", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__acceptFriendshipRequest(struct soap*, const struct ims__acceptFriendshipRequest *, const char*, const char*);

#ifndef soap_read_ims__acceptFriendshipRequest
#define soap_read_ims__acceptFriendshipRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__acceptFriendshipRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__acceptFriendshipRequest * SOAP_FMAC4 soap_get_ims__acceptFriendshipRequest(struct soap*, struct ims__acceptFriendshipRequest *, const char*, const char*);

#ifndef SOAP_TYPE_ims__acceptFriendshipRequestResponse
#define SOAP_TYPE_ims__acceptFriendshipRequestResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__acceptFriendshipRequestResponse(struct soap*, struct ims__acceptFriendshipRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__acceptFriendshipRequestResponse(struct soap*, const struct ims__acceptFriendshipRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__acceptFriendshipRequestResponse(struct soap*, const char*, int, const struct ims__acceptFriendshipRequestResponse *, const char*);
SOAP_FMAC3 struct ims__acceptFriendshipRequestResponse * SOAP_FMAC4 soap_in_ims__acceptFriendshipRequestResponse(struct soap*, const char*, struct ims__acceptFriendshipRequestResponse *, const char*);

#ifndef soap_write_ims__acceptFriendshipRequestResponse
#define soap_write_ims__acceptFriendshipRequestResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__acceptFriendshipRequestResponse(soap, data), 0) || soap_put_ims__acceptFriendshipRequestResponse(soap, data, "ims:acceptFriendshipRequestResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__acceptFriendshipRequestResponse(struct soap*, const struct ims__acceptFriendshipRequestResponse *, const char*, const char*);

#ifndef soap_read_ims__acceptFriendshipRequestResponse
#define soap_read_ims__acceptFriendshipRequestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__acceptFriendshipRequestResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__acceptFriendshipRequestResponse * SOAP_FMAC4 soap_get_ims__acceptFriendshipRequestResponse(struct soap*, struct ims__acceptFriendshipRequestResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriendshipRequests
#define SOAP_TYPE_ims__getFriendshipRequests (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriendshipRequests(struct soap*, struct ims__getFriendshipRequests *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriendshipRequests(struct soap*, const struct ims__getFriendshipRequests *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriendshipRequests(struct soap*, const char*, int, const struct ims__getFriendshipRequests *, const char*);
SOAP_FMAC3 struct ims__getFriendshipRequests * SOAP_FMAC4 soap_in_ims__getFriendshipRequests(struct soap*, const char*, struct ims__getFriendshipRequests *, const char*);

#ifndef soap_write_ims__getFriendshipRequests
#define soap_write_ims__getFriendshipRequests(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriendshipRequests(soap, data), 0) || soap_put_ims__getFriendshipRequests(soap, data, "ims:getFriendshipRequests", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriendshipRequests(struct soap*, const struct ims__getFriendshipRequests *, const char*, const char*);

#ifndef soap_read_ims__getFriendshipRequests
#define soap_read_ims__getFriendshipRequests(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriendshipRequests(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriendshipRequests * SOAP_FMAC4 soap_get_ims__getFriendshipRequests(struct soap*, struct ims__getFriendshipRequests *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriendshipRequestsResponse
#define SOAP_TYPE_ims__getFriendshipRequestsResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriendshipRequestsResponse(struct soap*, struct ims__getFriendshipRequestsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriendshipRequestsResponse(struct soap*, const struct ims__getFriendshipRequestsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriendshipRequestsResponse(struct soap*, const char*, int, const struct ims__getFriendshipRequestsResponse *, const char*);
SOAP_FMAC3 struct ims__getFriendshipRequestsResponse * SOAP_FMAC4 soap_in_ims__getFriendshipRequestsResponse(struct soap*, const char*, struct ims__getFriendshipRequestsResponse *, const char*);

#ifndef soap_write_ims__getFriendshipRequestsResponse
#define soap_write_ims__getFriendshipRequestsResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriendshipRequestsResponse(soap, data), 0) || soap_put_ims__getFriendshipRequestsResponse(soap, data, "ims:getFriendshipRequestsResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriendshipRequestsResponse(struct soap*, const struct ims__getFriendshipRequestsResponse *, const char*, const char*);

#ifndef soap_read_ims__getFriendshipRequestsResponse
#define soap_read_ims__getFriendshipRequestsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriendshipRequestsResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriendshipRequestsResponse * SOAP_FMAC4 soap_get_ims__getFriendshipRequestsResponse(struct soap*, struct ims__getFriendshipRequestsResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendFriendshipRequest
#define SOAP_TYPE_ims__sendFriendshipRequest (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendFriendshipRequest(struct soap*, struct ims__sendFriendshipRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendFriendshipRequest(struct soap*, const struct ims__sendFriendshipRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendFriendshipRequest(struct soap*, const char*, int, const struct ims__sendFriendshipRequest *, const char*);
SOAP_FMAC3 struct ims__sendFriendshipRequest * SOAP_FMAC4 soap_in_ims__sendFriendshipRequest(struct soap*, const char*, struct ims__sendFriendshipRequest *, const char*);

#ifndef soap_write_ims__sendFriendshipRequest
#define soap_write_ims__sendFriendshipRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendFriendshipRequest(soap, data), 0) || soap_put_ims__sendFriendshipRequest(soap, data, "ims:sendFriendshipRequest", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendFriendshipRequest(struct soap*, const struct ims__sendFriendshipRequest *, const char*, const char*);

#ifndef soap_read_ims__sendFriendshipRequest
#define soap_read_ims__sendFriendshipRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendFriendshipRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendFriendshipRequest * SOAP_FMAC4 soap_get_ims__sendFriendshipRequest(struct soap*, struct ims__sendFriendshipRequest *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendFriendshipRequestResponse
#define SOAP_TYPE_ims__sendFriendshipRequestResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendFriendshipRequestResponse(struct soap*, struct ims__sendFriendshipRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendFriendshipRequestResponse(struct soap*, const struct ims__sendFriendshipRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendFriendshipRequestResponse(struct soap*, const char*, int, const struct ims__sendFriendshipRequestResponse *, const char*);
SOAP_FMAC3 struct ims__sendFriendshipRequestResponse * SOAP_FMAC4 soap_in_ims__sendFriendshipRequestResponse(struct soap*, const char*, struct ims__sendFriendshipRequestResponse *, const char*);

#ifndef soap_write_ims__sendFriendshipRequestResponse
#define soap_write_ims__sendFriendshipRequestResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendFriendshipRequestResponse(soap, data), 0) || soap_put_ims__sendFriendshipRequestResponse(soap, data, "ims:sendFriendshipRequestResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendFriendshipRequestResponse(struct soap*, const struct ims__sendFriendshipRequestResponse *, const char*, const char*);

#ifndef soap_read_ims__sendFriendshipRequestResponse
#define soap_read_ims__sendFriendshipRequestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendFriendshipRequestResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendFriendshipRequestResponse * SOAP_FMAC4 soap_get_ims__sendFriendshipRequestResponse(struct soap*, struct ims__sendFriendshipRequestResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addFriend
#define SOAP_TYPE_ims__addFriend (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addFriend(struct soap*, struct ims__addFriend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addFriend(struct soap*, const struct ims__addFriend *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addFriend(struct soap*, const char*, int, const struct ims__addFriend *, const char*);
SOAP_FMAC3 struct ims__addFriend * SOAP_FMAC4 soap_in_ims__addFriend(struct soap*, const char*, struct ims__addFriend *, const char*);

#ifndef soap_write_ims__addFriend
#define soap_write_ims__addFriend(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addFriend(soap, data), 0) || soap_put_ims__addFriend(soap, data, "ims:addFriend", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addFriend(struct soap*, const struct ims__addFriend *, const char*, const char*);

#ifndef soap_read_ims__addFriend
#define soap_read_ims__addFriend(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addFriend(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addFriend * SOAP_FMAC4 soap_get_ims__addFriend(struct soap*, struct ims__addFriend *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addFriendResponse
#define SOAP_TYPE_ims__addFriendResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addFriendResponse(struct soap*, struct ims__addFriendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addFriendResponse(struct soap*, const struct ims__addFriendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addFriendResponse(struct soap*, const char*, int, const struct ims__addFriendResponse *, const char*);
SOAP_FMAC3 struct ims__addFriendResponse * SOAP_FMAC4 soap_in_ims__addFriendResponse(struct soap*, const char*, struct ims__addFriendResponse *, const char*);

#ifndef soap_write_ims__addFriendResponse
#define soap_write_ims__addFriendResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addFriendResponse(soap, data), 0) || soap_put_ims__addFriendResponse(soap, data, "ims:addFriendResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addFriendResponse(struct soap*, const struct ims__addFriendResponse *, const char*, const char*);

#ifndef soap_read_ims__addFriendResponse
#define soap_read_ims__addFriendResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addFriendResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addFriendResponse * SOAP_FMAC4 soap_get_ims__addFriendResponse(struct soap*, struct ims__addFriendResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__userLogin
#define SOAP_TYPE_ims__userLogin (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__userLogin(struct soap*, struct ims__userLogin *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__userLogin(struct soap*, const struct ims__userLogin *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__userLogin(struct soap*, const char*, int, const struct ims__userLogin *, const char*);
SOAP_FMAC3 struct ims__userLogin * SOAP_FMAC4 soap_in_ims__userLogin(struct soap*, const char*, struct ims__userLogin *, const char*);

#ifndef soap_write_ims__userLogin
#define soap_write_ims__userLogin(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__userLogin(soap, data), 0) || soap_put_ims__userLogin(soap, data, "ims:userLogin", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__userLogin(struct soap*, const struct ims__userLogin *, const char*, const char*);

#ifndef soap_read_ims__userLogin
#define soap_read_ims__userLogin(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__userLogin(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__userLogin * SOAP_FMAC4 soap_get_ims__userLogin(struct soap*, struct ims__userLogin *, const char*, const char*);

#ifndef SOAP_TYPE_ims__userLoginResponse
#define SOAP_TYPE_ims__userLoginResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__userLoginResponse(struct soap*, struct ims__userLoginResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__userLoginResponse(struct soap*, const struct ims__userLoginResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__userLoginResponse(struct soap*, const char*, int, const struct ims__userLoginResponse *, const char*);
SOAP_FMAC3 struct ims__userLoginResponse * SOAP_FMAC4 soap_in_ims__userLoginResponse(struct soap*, const char*, struct ims__userLoginResponse *, const char*);

#ifndef soap_write_ims__userLoginResponse
#define soap_write_ims__userLoginResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__userLoginResponse(soap, data), 0) || soap_put_ims__userLoginResponse(soap, data, "ims:userLoginResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__userLoginResponse(struct soap*, const struct ims__userLoginResponse *, const char*, const char*);

#ifndef soap_read_ims__userLoginResponse
#define soap_read_ims__userLoginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__userLoginResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__userLoginResponse * SOAP_FMAC4 soap_get_ims__userLoginResponse(struct soap*, struct ims__userLoginResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addUser
#define SOAP_TYPE_ims__addUser (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addUser(struct soap*, struct ims__addUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addUser(struct soap*, const struct ims__addUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addUser(struct soap*, const char*, int, const struct ims__addUser *, const char*);
SOAP_FMAC3 struct ims__addUser * SOAP_FMAC4 soap_in_ims__addUser(struct soap*, const char*, struct ims__addUser *, const char*);

#ifndef soap_write_ims__addUser
#define soap_write_ims__addUser(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addUser(soap, data), 0) || soap_put_ims__addUser(soap, data, "ims:addUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addUser(struct soap*, const struct ims__addUser *, const char*, const char*);

#ifndef soap_read_ims__addUser
#define soap_read_ims__addUser(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addUser * SOAP_FMAC4 soap_get_ims__addUser(struct soap*, struct ims__addUser *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addUserResponse
#define SOAP_TYPE_ims__addUserResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addUserResponse(struct soap*, struct ims__addUserResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addUserResponse(struct soap*, const struct ims__addUserResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addUserResponse(struct soap*, const char*, int, const struct ims__addUserResponse *, const char*);
SOAP_FMAC3 struct ims__addUserResponse * SOAP_FMAC4 soap_in_ims__addUserResponse(struct soap*, const char*, struct ims__addUserResponse *, const char*);

#ifndef soap_write_ims__addUserResponse
#define soap_write_ims__addUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addUserResponse(soap, data), 0) || soap_put_ims__addUserResponse(soap, data, "ims:addUserResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addUserResponse(struct soap*, const struct ims__addUserResponse *, const char*, const char*);

#ifndef soap_read_ims__addUserResponse
#define soap_read_ims__addUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addUserResponse * SOAP_FMAC4 soap_get_ims__addUserResponse(struct soap*, struct ims__addUserResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__receiveMessage
#define SOAP_TYPE_ims__receiveMessage (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__receiveMessage(struct soap*, struct ims__receiveMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__receiveMessage(struct soap*, const struct ims__receiveMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__receiveMessage(struct soap*, const char*, int, const struct ims__receiveMessage *, const char*);
SOAP_FMAC3 struct ims__receiveMessage * SOAP_FMAC4 soap_in_ims__receiveMessage(struct soap*, const char*, struct ims__receiveMessage *, const char*);

#ifndef soap_write_ims__receiveMessage
#define soap_write_ims__receiveMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__receiveMessage(soap, data), 0) || soap_put_ims__receiveMessage(soap, data, "ims:receiveMessage", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__receiveMessage(struct soap*, const struct ims__receiveMessage *, const char*, const char*);

#ifndef soap_read_ims__receiveMessage
#define soap_read_ims__receiveMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__receiveMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__receiveMessage * SOAP_FMAC4 soap_get_ims__receiveMessage(struct soap*, struct ims__receiveMessage *, const char*, const char*);

#ifndef SOAP_TYPE_ims__receiveMessageResponse
#define SOAP_TYPE_ims__receiveMessageResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__receiveMessageResponse(struct soap*, struct ims__receiveMessageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__receiveMessageResponse(struct soap*, const struct ims__receiveMessageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__receiveMessageResponse(struct soap*, const char*, int, const struct ims__receiveMessageResponse *, const char*);
SOAP_FMAC3 struct ims__receiveMessageResponse * SOAP_FMAC4 soap_in_ims__receiveMessageResponse(struct soap*, const char*, struct ims__receiveMessageResponse *, const char*);

#ifndef soap_write_ims__receiveMessageResponse
#define soap_write_ims__receiveMessageResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__receiveMessageResponse(soap, data), 0) || soap_put_ims__receiveMessageResponse(soap, data, "ims:receiveMessageResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__receiveMessageResponse(struct soap*, const struct ims__receiveMessageResponse *, const char*, const char*);

#ifndef soap_read_ims__receiveMessageResponse
#define soap_read_ims__receiveMessageResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__receiveMessageResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__receiveMessageResponse * SOAP_FMAC4 soap_get_ims__receiveMessageResponse(struct soap*, struct ims__receiveMessageResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendMessage
#define SOAP_TYPE_ims__sendMessage (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendMessage(struct soap*, struct ims__sendMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendMessage(struct soap*, const struct ims__sendMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendMessage(struct soap*, const char*, int, const struct ims__sendMessage *, const char*);
SOAP_FMAC3 struct ims__sendMessage * SOAP_FMAC4 soap_in_ims__sendMessage(struct soap*, const char*, struct ims__sendMessage *, const char*);

#ifndef soap_write_ims__sendMessage
#define soap_write_ims__sendMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendMessage(soap, data), 0) || soap_put_ims__sendMessage(soap, data, "ims:sendMessage", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendMessage(struct soap*, const struct ims__sendMessage *, const char*, const char*);

#ifndef soap_read_ims__sendMessage
#define soap_read_ims__sendMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendMessage * SOAP_FMAC4 soap_get_ims__sendMessage(struct soap*, struct ims__sendMessage *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendMessageResponse
#define SOAP_TYPE_ims__sendMessageResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendMessageResponse(struct soap*, struct ims__sendMessageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendMessageResponse(struct soap*, const struct ims__sendMessageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendMessageResponse(struct soap*, const char*, int, const struct ims__sendMessageResponse *, const char*);
SOAP_FMAC3 struct ims__sendMessageResponse * SOAP_FMAC4 soap_in_ims__sendMessageResponse(struct soap*, const char*, struct ims__sendMessageResponse *, const char*);

#ifndef soap_write_ims__sendMessageResponse
#define soap_write_ims__sendMessageResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendMessageResponse(soap, data), 0) || soap_put_ims__sendMessageResponse(soap, data, "ims:sendMessageResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendMessageResponse(struct soap*, const struct ims__sendMessageResponse *, const char*, const char*);

#ifndef soap_read_ims__sendMessageResponse
#define soap_read_ims__sendMessageResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendMessageResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendMessageResponse * SOAP_FMAC4 soap_get_ims__sendMessageResponse(struct soap*, struct ims__sendMessageResponse *, const char*, const char*);

#ifndef SOAP_TYPE_Char_vector
#define SOAP_TYPE_Char_vector (11)
#endif

#define soap_default_Char_vector(soap, a) soap_default__Struct_1(soap, a)


#define soap_serialize_Char_vector(soap, a) soap_serialize__Struct_1(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_Char_vector(struct soap*, const char*, int, const struct _Struct_1 *, const char*);
SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_in_Char_vector(struct soap*, const char*, struct _Struct_1 *, const char*);

#ifndef soap_write_Char_vector
#define soap_write_Char_vector(soap, data) ( soap_begin_send(soap) || (soap_serialize_Char_vector(soap, data), 0) || soap_put_Char_vector(soap, data, "Char-vector", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Char_vector(struct soap*, const struct _Struct_1 *, const char*, const char*);

#ifndef soap_read_Char_vector
#define soap_read_Char_vector(soap, data) ( soap_begin_recv(soap) || !soap_get_Char_vector(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_get_Char_vector(struct soap*, struct _Struct_1 *, const char*, const char*);

#ifndef SOAP_TYPE__Struct_1
#define SOAP_TYPE__Struct_1 (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Struct_1(struct soap*, struct _Struct_1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__Struct_1(struct soap*, const struct _Struct_1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Struct_1(struct soap*, const char*, int, const struct _Struct_1 *, const char*);
SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_in__Struct_1(struct soap*, const char*, struct _Struct_1 *, const char*);

#ifndef soap_write__Struct_1
#define soap_write__Struct_1(soap, data) ( soap_begin_send(soap) || (soap_serialize__Struct_1(soap, data), 0) || soap_put__Struct_1(soap, data, "Struct-1", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__Struct_1(struct soap*, const struct _Struct_1 *, const char*, const char*);

#ifndef soap_read__Struct_1
#define soap_read__Struct_1(soap, data) ( soap_begin_recv(soap) || !soap_get__Struct_1(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_get__Struct_1(struct soap*, struct _Struct_1 *, const char*, const char*);

#ifndef SOAP_TYPE_Message
#define SOAP_TYPE_Message (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Message(struct soap*, struct Message *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Message(struct soap*, const struct Message *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Message(struct soap*, const char*, int, const struct Message *, const char*);
SOAP_FMAC3 struct Message * SOAP_FMAC4 soap_in_Message(struct soap*, const char*, struct Message *, const char*);

#ifndef soap_write_Message
#define soap_write_Message(soap, data) ( soap_begin_send(soap) || (soap_serialize_Message(soap, data), 0) || soap_put_Message(soap, data, "Message", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Message(struct soap*, const struct Message *, const char*, const char*);

#ifndef soap_read_Message
#define soap_read_Message(soap, data) ( soap_begin_recv(soap) || !soap_get_Message(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct Message * SOAP_FMAC4 soap_get_Message(struct soap*, struct Message *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerToChar_vector
#define SOAP_TYPE_PointerToChar_vector (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToChar_vector(struct soap*, struct _Struct_1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToChar_vector(struct soap*, const char *, int, struct _Struct_1 *const*, const char *);
SOAP_FMAC3 struct _Struct_1 ** SOAP_FMAC4 soap_in_PointerToChar_vector(struct soap*, const char*, struct _Struct_1 **, const char*);

#ifndef soap_write_PointerToChar_vector
#define soap_write_PointerToChar_vector(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToChar_vector(soap, data), 0) || soap_put_PointerToChar_vector(soap, data, "Char-vector", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToChar_vector(struct soap*, struct _Struct_1 *const*, const char*, const char*);

#ifndef soap_read_PointerToChar_vector
#define soap_read_PointerToChar_vector(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToChar_vector(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_1 ** SOAP_FMAC4 soap_get_PointerToChar_vector(struct soap*, struct _Struct_1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToMessage
#define SOAP_TYPE_PointerToMessage (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToMessage(struct soap*, struct Message *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToMessage(struct soap*, const char *, int, struct Message *const*, const char *);
SOAP_FMAC3 struct Message ** SOAP_FMAC4 soap_in_PointerToMessage(struct soap*, const char*, struct Message **, const char*);

#ifndef soap_write_PointerToMessage
#define soap_write_PointerToMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToMessage(soap, data), 0) || soap_put_PointerToMessage(soap, data, "Message", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToMessage(struct soap*, struct Message *const*, const char*, const char*);

#ifndef soap_read_PointerToMessage
#define soap_read_PointerToMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct Message ** SOAP_FMAC4 soap_get_PointerToMessage(struct soap*, struct Message **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data), 0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__string(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_xsd__string
#define soap_write_xsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__string(soap, data), 0) || soap_put_xsd__string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_xsd__string
#define soap_read_xsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_Array100Ofstring
#define SOAP_TYPE_Array100Ofstring (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array100Ofstring(struct soap*, char *[100]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array100Ofstring(struct soap*, char *const[100]);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array100Ofstring(struct soap*, const char*, int, char *const[100], const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_in_Array100Ofstring(struct soap*, const char*, char *[100], const char*);

#ifndef soap_write_Array100Ofstring
#define soap_write_Array100Ofstring(soap, data) ( soap_begin_send(soap) || (soap_serialize_Array100Ofstring(soap, data), 0) || soap_put_Array100Ofstring(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array100Ofstring(struct soap*, char *const[100], const char*, const char*);

#ifndef soap_read_Array100Ofstring
#define soap_read_Array100Ofstring(soap, data) ( soap_begin_recv(soap) || !soap_get_Array100Ofstring(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * * SOAP_FMAC4 soap_get_Array100Ofstring(struct soap*, char *[100], const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
